MODULES=modules
ENVIRONMENT=$(basename $PWD)
echo -e "# Generated by $(basename $0)    $(date)\n\n"

for MOD_PATH in $MODULES/*; do
  MOD=$(basename $MOD_PATH)
  #echo "#  $MOD"
  if [ -d "$MOD_PATH/.git" ]; then
    echo " - Skipping local mod '$MOD'"
  else
    MOD_EXTERNAL_NAME=$(
      puppet module list --environment=$ENVIRONMENT \
      | grep -e "-$MOD " \
      | sed -e 's/-/\//' \
      | awk -F [\(\)\ ] '{print $2}')

    puppet module upgrade $MOD_EXTERNAL_NAME --force --environment=$ENVIRONMENT
  fi

  echo -e "\n"
done

